### ISSUE TITLE
Missing import/export items

### ISSUE THREAD

**Issue by TicTak21** [brandongit2/nestjs-redis#1]
After reading README example I found that there is a problem with imports/exports:

1) `Redis` interface should be imported from `ioredis`:

```ts
import { Redis } from 'ioredis';
```
Instead
```ts
import { Redis } from "nestjs-redis"
```
Due to import/export error: 
`Module '"nestjs-redis"' has no exported member 'Redis'`

2) Missing `InjectRedis` decorator:

This doesn't work: 
```ts
import { InjectRedis } from 'nestjs-redis';
```

After digging in `node_modules` I found that there is no such files like `decorator`(screenshot #1)
![nestjs-redis-files](https://user-images.githubusercontent.com/44474697/128600658-aebed962-4771-4f0c-8597-d45df11530ab.png)

And some imports are missing(screenshot #2)
![nestjs-redis-imports](https://user-images.githubusercontent.com/44474697/128600694-b1e311f4-f15a-4915-b1fa-7d8bcc68164f.png)

**Comment by brandongit2** [comment]
Hey, it seems there was a typo in the readme. I've updated it, can you try following the examples again?

Mistakenly used `nestjs-redis` instead of `@brandonnpm2/nestjs-redis`. Try doing `yarn remove nestjs-redis` and `yarn add @brandonnpm2/nestjs-redis`. Sorry about that.

**Comment by TicTak21** [comment]
No problem. Glad we were able to figure it out. 

Looks like everything is working now.
